apiVersion: apps/v1
kind: Deployment
metadata:
    name: hello-whale
spec:
    selector:
      matchLabels:
        app: hello-whale
    template:
      metadata:
        labels:
            app: hello-whale
      spec:
        containers:
        - name: hello-whale
          image: suman/hellowhale
