apiVersion: skaffold/v1alpha2
kind: Config
build:
  tagPolicy:
    gitCommit: {}      
  artifacts:
  - imageName: suman/hellowhale
    workspace: .
  local: {}

deploy:
  kubectl:
    manifests:
      - k8s-*
